### ISSUE TITLE
Renames?

### ISSUE THREAD

**Issue by Hoverbear** [Hoverbear/raft#70]
On page two of  [@ongardie's paper](http://ramcloud.stanford.edu/raft.pdf) the names of the components in the diagram are `StateMachine`, `Log`, `ConsensusModule`, and `Server`.

Roughly:

Current Impl | Paper
----------------|----------
`StateMachine` | `StateMachine`
`Store` | `Log`
`Replica` | `Consensus`
`Server` | `Server`
`Client` | `Client`

Should we do any renaming? Would this improve clarity? Are they appropriate?

**Comment by ycoady** [comment]
My sense is this could be helpful in allowing people most easily compare/contrast your implementation with [others]  (https://raftconsensus.github.io/) out there---but I can also do a quick pass to see if those others are being consistent!

**Comment by Hoverbear** [comment]
@ycoady We're on that list, too!

**Comment by ycoady** [comment]
Yes yes I know, *and* the only Rust one (go figure!)

**Comment by danburkert** [comment]
I'm in support of renaming `Store` to `Log`.  I'm also in support of renaming `Replica` since I don't think it's very descriptive, but I don't think `ConsensusModule` is much better (mostly I object to 'Module' since it's meaningless and could be confused with Rust's concept of modules).  It looks like logcabin's equivalent is [RaftConsensus](https://github.com/logcabin/logcabin/blob/master/Server/RaftConsensus.h#L883), etcd's is [raft](https://github.com/coreos/etcd/blob/master/raft/raft.go#L125), and Hashicorp's is [Raft](https://github.com/hashicorp/raft/blob/master/raft.go#L71).  I think of the bunch `RaftConsensus` or just `Consensus` is the best, but there's almost certainly a better name out there.  Rust (standard library) does have a [tradition](https://github.com/rust-lang/rfcs/blob/master/text/0356-no-module-prefixes.md) of not including the same identifier in module and type names (so for instance the same name in the module and type name, so for instance `raft::RaftConsensus` would be discouraged in favor of `raft::Consensus`.

**Comment by Hoverbear** [comment]
I'll make a PR once #67 is closed.

**Comment by ongardie** [comment]
I agree with @danburkert . The "Consensus Module" name isn't very good, but just calling it Consensus or Raft should help people find it.

LogCabin was initially meant to implement Paxos, btw. There was an interface named Consensus that RaftConsensus and PaxosConsensus were supposed to implement. PaxosConsensus never materialized into something worthy of committing, then RaftConsensus did, the Paxos attempt was abandoned, and Consensus was just merged into RaftConsensus.

**Comment by Hoverbear** [comment]
I noted `log` as a module would conflict, so I used `persistent_log`.
